### ISSUE TITLE
[New Feature] Create A Swift Website Type

### ISSUE THREAD

**Issue by mikebronner** [CodePier/CodePier-Issues#2]
When creating a new site, it would be great to add a new entry under the "Language & Framework" dropdown:

Swift
 - Vapor

> This can later be expanded to include the following frameworks as we figure out what their needs are:
> - Perfect
> - Kitura

Setting up a swift web site has specific server requirements:

### Server
**Distro**
- Ubuntu 16.04 (important, 18.04 does not work yet)

**Post-Install Script**
```sh
wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | sudo apt-key add -
echo "deb https://repo.vapor.codes/apt $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/vapor.list
apt-get update -y
apt-get install swift vapor -y
```

### Environment Variables
- these will need to be set up (in leu of using a `.env` file) during the site setup process.

### Cron Jobs
None needed by default.

### Daemon
A daemon will need to be set up per site. This will get a bit tricky, but if we can assign each site a numerical ID automatically that corresponds to the internal port being used, with the first site starting at 8080 and incrementing by one for each additional site. The port/site-id will come into play here, as well as in the Nginx configuration file:

**Command**
```
/home/codepier/<site-folder>/.build/release/Run --hostname 127.0.0.1 --port <site-port>
```

**Working Directory**
```
/home/codepier/<site-folder>
```

The Nginx's `sites-enabled/<site-folder>` file would look like this:
```
server {
#add ssl redirect and listener on port 443 as well
    listen 80;
    listen [::]:80;
    server_name <site-folder>;
    root /home/codepier/,site-filder>/Public;

    charset utf-8;

    location / {
        try_files $uri @proxy;
    }

    location @proxy {
        proxy_pass http://127.0.0.1:<site-port>;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/vaportest.genealabs.com-error.log error;

    error_page 404 /index.php;

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

### Workers
None needed by default.

### Server Files
None needed by default.

### Language Settings
No Swift settings I can think of at this time.

### Server Features
**Database Features**
- MySQL (optional)
- PostgreSQL (optional)
- Redis (optional, but likely used)
- Memcached (not used, that I know of)
- SqLite (optional)
- MongoDB (optional)

**Firewall Features**
- Fail2Ban (suggested, to prevent SSH brute force hack attempts)

**Monitoring Features**
- All (optional, but suggest to have them all)

**Node Features**
- None (optional, not normally needed, but some workflows may use them)

**OS Features**
- Swap (default)
- Docker (optional, some workflows will use docker containers to develop swift sites)

**Repositor Features**
- Git (required)

**Web Features**
- CertBot (required)
- Nginx (required)

**Worker Features**
- Beanstalk (optional, probably not used)
- Supervisor (required)

**PHP Features**
- None

**Comment by mikebronner** [comment]
@lukepolo  This is a pretty big list, let me know if anything is unclear or you would like to discuss in more detail. :) Thanks!

**Comment by lukepolo** [comment]
@mikebronner Thanks! No problem, it sounds really doable , Could you get me a list of deployment steps too that you will need to deploy your app?

**Comment by mikebronner** [comment]
- deployment through GitHub web hooks when master is updated
- everything else just like laravel

**Comment by lukepolo** [comment]
We deployed this a while ago forgot to close the issue.
