### ISSUE TITLE
Deploying Laravel site uses Laravel Cache Routes

### ISSUE THREAD

**Issue by cringer** [CodePier/CodePier-Issues#20]
### Browser and Version
Chrome 55.0.2883

### Steps to reproduce
1. Create new site
2. Provision Site

### What is Expected?
Under Deployment under site setup "Laravel Cache Routes" is ACTIVE.  It should be INACTIVE with "Install Node Dependencies."  

### What is actually happening?
The reason is that by default laravel routes files have route closures.  Possibly someones project may as well.  You cannot use route caching if you have ANY route closures so this will cause deployment failure in these cases.

**Comment by dmfj** [comment]
This is a good point, @cringer. Thanks.

**Comment by lukepolo** [comment]
Will move those to inactive and can be dragged over if they want to activate them ~ will be in next release
